apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prd-iris-agent
  name: prd-iris-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-iris-agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prd-iris-agent
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/iris-agent:14377617032
        name: iris-agent
        resources: {}
status: {}
