apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prd-places
  name: prd-places
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-places
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prd-places
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/places-prod:13670043954
        name: places-prod
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
status: {}