apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prd-frontend
  name: prd-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prd-frontend
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/prd-frontend:13494855851
        name: prd-frontend
        resources: {}
status: {}
