apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prd-misc-api
  name: prd-misc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-misc-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prd-misc-api
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/misc-api:15208145978
        name: prd-misc-api
status: {}