apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prd-candidate-report
  name: prd-candidate-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-candidate-report
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prd-candidate-report
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/prd-candidate-report:16464135092
        name: prd-candidate-report
status: {}