apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prd-av-agent-server
  name: prd-av-agent-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-av-agent-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prd-av-agent-server
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/prd-av-agent-server:16775418894
        name: prd-av-agent-server
status: {}