apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prd-inference
  name: prd-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-inference
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prd-inference
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/inference-prod:14374894577
        name: prd-inference
        resources: {}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8900
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8900
          initialDelaySeconds: 90
          periodSeconds: 5
status: {}