apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prd-backend
  name: prd-backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: prd-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: prd-backend
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/prd-backend:18676011824
        name: prd-backend
        resources:
          requests:
            cpu: "700m"
            memory: "1100Mi"
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 4003
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: prd-backend