apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prd-iris-agent-v2
  name: prd-iris-agent-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-iris-agent-v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prd-iris-agent-v2
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/prd-iris-agent-v2:16620362810
        name: prd-iris-agent-v2
        resources: {}
status: {}
