apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rag-candidate-livekit
  name: rag-candidate-livekit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-candidate-livekit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rag-candidate-livekit
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-prod-repo/rag-candidate-livekit:15898493664
        name: rag-candidate-livekit
status: {}