apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: data-streaming-mixpanel
  name: data-streaming-mixpanel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-streaming-mixpanel
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: data-streaming-mixpanel
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/data-streaming-mixpanel:19428225901
        name: data-streaming-mixpanel
status: {}