apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: data-streaming-server
  name: data-streaming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-streaming-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: data-streaming-server
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/data-streaming-server:19428041493
        name: data-streaming-server
status: {}