apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: data-streaming-gcs
  name: data-streaming-gcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-streaming-gcs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: data-streaming-gcs
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/data-streaming-gcs:19499221825
        name: data-streaming-gcs
status: {}