apiVersion: batch/v1
kind: CronJob
metadata:
  name: elfsight-cron
spec:
  schedule: "0 * * * *"
  timeZone: "Asia/Karachi"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: elfsight
            image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/elfsight:18370949517
          restartPolicy: Never