apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-qureos-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-qureos-com
  template:
    metadata:
      labels:
        app: job-qureos-com
    spec:
      containers:
      - name: job-qureos-com
        image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/job-qureos-com:17944486106