apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stg-candidate-server-v3
  name: stg-candidate-server-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stg-candidate-server-v3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stg-candidate-server-v3
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/stg-candidate-server-v3:16562444859
        name: stg-candidate-server-v3
status: {}