apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stg-iris-agent-v2
  name: stg-iris-agent-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stg-iris-agent-v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stg-iris-agent-v2
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/stg-iris-agent-v2:16187302907
        name: stg-iris-agent-v2
        resources: {}
status: {}
