apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stg-inference
  name: stg-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stg-inference
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stg-inference
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/inference:12387903974
        name: inference
        resources: {}
status: {}
