apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stg-backend
  name: stg-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stg-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stg-backend
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/stg-backend:12594251456
        name: stg-backend
        resources: {}
status: {}
