apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stg-candidate-report
  name: stg-candidate-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stg-candidate-report
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stg-candidate-report
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/stg-candidate-report:18374273668
        name: stg-candidate-report
status: {}