apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stg-iris-agent
  name: stg-iris-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stg-iris-agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stg-iris-agent
    spec:
      containers:
        env:
        - name: PROMPT_MAKER_API
          valueFrom:
            secretKeyRef:
              name: stg-iris-agent
              key: PROMPT_MAKER_API
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/stg-iris-agent:13365068045
        name: stg-iris-agent
        resources: {}
status: {}
