apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stg-recruiter-referral
  name: stg-recruiter-referral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stg-recruiter-referral
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stg-recruiter-referral
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/stg-recruiter-referral:17209664879
        name: stg-recruiter-referral
status: {}