apiVersion: batch/v1
kind: CronJob
metadata:
  name: teamtailor-candidate-aquisition-cron
spec:
  schedule: "0 8 * * *"
  timeZone: "Asia/Karachi"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: teamtailor-candidate-aquisition
            image: europe-west1-docker.pkg.dev/qureos-mig-gke/qureos-stg-repo/teamtailor-candidate-aquisition:16187312878
          restartPolicy: Never